Feat/swrinfo 184/tcp proto
SwarmUS/HiveAR pull request #14
Opened 2021-02-15 19:57 UTC by t-constantin

-Send proto messages (moveBy for now)
-Receive and log proto messages
-Fix some issue when entering ip/port for tcp

2021-02-15 20:06 UTC, stlaperriere commented on HiveAR/app/src/main/java/com/swarmus/hivear/models/SerialDevice.java
> +        endConnection();
Why the need to end the connection when you establish a new one?

2021-02-15 20:11 UTC, stlaperriere commented on HiveAR/app/src/main/java/com/swarmus/hivear/models/SerialDevice.java
> +            pipedInputStream = new PipedInputStream();
Would it be pertinent to to a check to see if the piped stream already exists (maybe just print a warning for debugging purposes)?

2021-02-15 20:54 UTC, stlaperriere requested changes
GJ, a few questions and a little something about some incoming breaking changes in Propolis

2021-02-15 20:54 UTC, stlaperriere commented on HiveAR/app/src/main/java/com/swarmus/hivear/models/SerialDevice.java
> +                Log.e(DEVICE_INFO_LOG_TAG, "Could open pipe for UART data stream");
could NOT open (...)

2021-02-15 20:54 UTC, stlaperriere commented on HiveAR/app/src/main/java/com/swarmus/hivear/fragments/TcpSettingsFragment.java
> +                    }
Is it me or this code is exactly the same as lines 31 to 40? Except maybe for the call to `clearFocus`. Is that wanted, and if so, why?

2021-02-15 20:54 UTC, stlaperriere commented on HiveAR/app/src/main/java/com/swarmus/hivear/commands/MoveByCommand.java
> +            UserCall.UserCallDestination userCallDestination = UserCall.UserCallDestination.HOST;
Xavier just pushed some code in Propolis that you'll want to look at. There are some small (breaking) changes on the definition of this structure. You could also adapt your code in a future PR if you prefer.

https://github.com/SwarmUS/Propolis/pull/12/files

2021-02-15 20:54 UTC, stlaperriere commented on HiveAR/app/src/main/java/com/swarmus/hivear/commands/GenericCommand.java
> +    protected MessageOuterClass.Message moveByMessage;
Your `GenericCommand` class has a `moveByMessage`? This looks specific to the `MoveByCommand` class. You could also try to use dependency injection to provide the message to the classif you think it appropriate. We do this a lot in the C++ code. See: https://fr.wikipedia.org/wiki/Injection_de_d%C3%A9pendances

Also, have you considered making this class an interface instead?  This seems very generic, do you think you will need to implement some methods in the super classes or is everything destined to be overridden?

2021-02-16 03:24 UTC, t-constantin commented on HiveAR/app/src/main/java/com/swarmus/hivear/models/SerialDevice.java
> +        endConnection();
In case previous connection wasn't correctly closed, we want to assure that only a single connection can be openned at the same time

2021-02-16 17:20 UTC, t-constantin commented on HiveAR/app/src/main/java/com/swarmus/hivear/fragments/TcpSettingsFragment.java
> +                    }
Forgot to remove when, nice thing you saw it!

2021-02-16 17:29 UTC, t-constantin commented on HiveAR/app/src/main/java/com/swarmus/hivear/commands/MoveByCommand.java
> +            UserCall.UserCallDestination userCallDestination = UserCall.UserCallDestination.HOST;
ok, I updated it

2021-02-16 17:32 UTC, t-constantin commented on HiveAR/app/src/main/java/com/swarmus/hivear/commands/GenericCommand.java
> +    protected MessageOuterClass.Message moveByMessage;
Changed moveByMessage to message.

I wanted to have an abstract class to overide methods, but I can't use interface as we have the message attribute.
I want to be able to construct a protobuf message and keep it instead of creating always a new one each time we want to send a message. This way, with redundant user commands, we will only need to pass the existing message if already created

2021-02-16 21:26 UTC, stlaperriere approved these changes

2021-02-16 22:53 UTC, merged