Feat/swarinfo 159/robot details
SwarmUS/HiveAR pull request #19
Opened 2021-02-19 15:26 UTC by t-constantin

Simple UI to create a list of robots + unique details view from each robot.
For now: creates commands based on a String List in the robot
We cannot send proto request command from Robot Details view for now as it won't work in simulation.

Swarm Summary View: (Shows RObot Name + its swarm UID)
![image](https://user-images.githubusercontent.com/34560270/108523295-bcebcf00-729b-11eb-85c9-c9082bcae54a.png)

Robot details view: Shows Robot icon, Robot name, its swarm UID and list commands
    Commands list: Shows command name, send command button, then argument list
        Argument list: Show Argument name and input with specifi text input base on the argument
![image](https://user-images.githubusercontent.com/34560270/108523522-03412e00-729c-11eb-8373-a6f94d2b1610.png)

2021-02-19 16:07 UTC, cquesnel requested changes

2021-02-19 16:07 UTC, cquesnel commented on HiveAR/app/src/main/java/com/swarmus/hivear/factories/CommandArgumentViewFactory.java
> +            case moveBy:
Same comment on hardcoding the structure of commands. I know this is juste a demo, but I would make something more generic than what is done here.

2021-02-19 16:07 UTC, cquesnel commented on HiveAR/app/src/main/java/com/swarmus/hivear/factories/CommandArgumentViewFactory.java
> +            case moveBy:
It could also be plugged into protobuf as we already have a generic way of handling function calls with an indeterminate number of arguments

2021-02-19 17:13 UTC, t-constantin commented on HiveAR/app/src/main/java/com/swarmus/hivear/factories/CommandArgumentViewFactory.java
> +            case moveBy:
It would be nice to also have an attribute for proto FunctionArgument to have a name for description purpose.
Else, we only have a list of arguments which we need to remember to order from one application to another

2021-02-19 17:57 UTC, t-constantin commented on HiveAR/app/src/main/java/com/swarmus/hivear/factories/CommandArgumentViewFactory.java
> +    public static List<View> createCommandArgumentViews(LayoutInflater inflater, CommandType commandType) {
Give parent instead of inflater (itemView in RobotCommandsAdapter), then retrieve inflater with: parent.getContext()

2021-02-23 13:05 UTC, cquesnel approved these changes

2021-02-23 13:09 UTC, merged