SWARINFO-278 QR Code + add image at runtime
SwarmUS/HiveAR pull request #27
Opened 2021-03-19 15:07 UTC by t-constantin

New workflow:
Settings view : Visualize current AR Database content + select/add/delete databases.
From selected, ar view will start tracking the database content.

From settings view, possible to go to QR view
QR view:
   -Generate tags from name/uid/description (to use on robot)
   -Add to database from QR Code (scan to track)

Settings view
![Screenshot_20210319-110545_HiveAR](https://user-images.githubusercontent.com/34560270/111801310-35e24480-88a3-11eb-8780-566aa2d6e337.jpg)

QR Code view
![Screenshot_20210319-110603_HiveAR](https://user-images.githubusercontent.com/34560270/111801362-42669d00-88a3-11eb-8d2f-16a861340855.jpg)

2021-03-19 18:44 UTC, stlaperriere commented on HiveAR/app/src/main/java/com/swarmus/hivear/fragments/ARViewFragment.java
> +            arFragment.getArSceneView().getScene().addOnUpdateListener(frameTime -> updateFrame(frameTime));
Why did you remove the try.. catch block?

2021-03-19 19:44 UTC, stlaperriere requested changes
GJ, that was a big chunk! A few minor comments.

2021-03-19 19:44 UTC, stlaperriere commented on HiveAR/app/src/main/java/com/swarmus/hivear/fragments/QRScanFragment.java
> +        File mydir = new File(settingsViewModel.getActiveFolderAbsolutePath());
`mydir`, my dear!

We might want to call this variable by another name (it looks like it comes from a tutorial :stuck_out_tongue_closed_eyes: )

2021-03-19 19:44 UTC, stlaperriere commented on HiveAR/app/src/main/java/com/swarmus/hivear/fragments/SettingsFragment.java
> +        builder.setTitle("Add new Database Folder");
Shouldn't this string be in `strings.xml` ?

2021-03-19 19:44 UTC, stlaperriere commented on HiveAR/app/src/main/java/com/swarmus/hivear/fragments/SettingsFragment.java
> +        builder.setPositiveButton("Add", new DialogInterface.OnClickListener() {
Shouldn't this string be in `strings.xml` ?

2021-03-19 19:44 UTC, stlaperriere commented on HiveAR/app/src/main/java/com/swarmus/hivear/fragments/SettingsFragment.java
> +        builder.setNegativeButton("Cancel", new DialogInterface.OnClickListener() {
Shouldn't this string be in `strings.xml` ?

2021-03-19 19:44 UTC, stlaperriere commented on HiveAR/app/src/main/java/com/swarmus/hivear/fragments/QRScanFragment.java
> +            }
Actually, would a Toast be a good option here instead of printing the stack trace?

2021-03-20 12:45 UTC, t-constantin commented on HiveAR/app/src/main/java/com/swarmus/hivear/fragments/ARViewFragment.java
> +            arFragment.getArSceneView().getScene().addOnUpdateListener(frameTime -> updateFrame(frameTime));
I was loading an existing databse from a file which could cause an exception. Now, we add images at runtime and therefore, no more loading file here

2021-03-20 12:48 UTC, t-constantin commented on HiveAR/app/src/main/java/com/swarmus/hivear/fragments/QRScanFragment.java
> +            }
To button is only visible when there is a QR result in the decoder

2021-03-20 12:49 UTC, t-constantin commented on HiveAR/app/src/main/java/com/swarmus/hivear/fragments/QRScanFragment.java
> +            }
However the toast is a good idea here

2021-03-20 12:52 UTC, t-constantin commented on HiveAR/app/src/main/java/com/swarmus/hivear/fragments/QRScanFragment.java
> +            public void surfaceChanged(@NonNull SurfaceHolder surfaceHolder, int i, int i1, int i2) {
Function need to be overrided when implementing the interface, however, I don't need anything done here.
Names will be changed, those were the default generated ones

2021-03-20 12:54 UTC, t-constantin commented on HiveAR/app/src/main/java/com/swarmus/hivear/fragments/QRScanFragment.java
> +        File mydir = new File(settingsViewModel.getActiveFolderAbsolutePath());
Guilty 😂

2021-03-20 13:06 UTC, stlaperriere approved these changes

2021-03-20 13:07 UTC, merged