Feat/swarinfo 362/tcp server implementation to connect to host
SwarmUS/HiveAR pull request #43
Opened 2021-04-07 02:37 UTC by g-lesssard

2021-04-07 13:07 UTC, t-constantin requested changes

2021-04-07 13:07 UTC, t-constantin commented on HiveAR/app/src/main/java/com/swarmus/hivear/models/TCPDeviceServer.java
> +                connectionCallback.onConnectError();
should add :
currentStatus = ConnectionStatus = ConnectionStatus.notConnected;

2021-04-07 13:12 UTC, t-constantin requested changes

2021-04-07 13:12 UTC, t-constantin commented on HiveAR/app/src/main/java/com/swarmus/hivear/activities/MainActivity.java
> +    private static final String DEFAULT_IP_ADDRESS = "10.0.2.15.";
remove "." at the end of IP string

2021-04-07 13:12 UTC, t-constantin commented on HiveAR/app/src/main/java/com/swarmus/hivear/models/TCPDeviceServer.java
> +// use address 10.0.2.15m which corresponds to the emulated network interface in the emulator.
typo  "m" concatenated with IP string

2021-04-07 13:12 UTC, t-constantin commented on HiveAR/app/src/main/java/com/swarmus/hivear/models/TCPDeviceServer.java
> +                connectionCallback.onConnectError();
also, should close socket as it is not close after timeout. (just like line 68)

2021-04-09 11:24 UTC, t-constantin requested changes
Minor things to change / correct

2021-04-09 11:24 UTC, t-constantin commented on HiveAR/app/src/main/java/com/swarmus/hivear/activities/MainActivity.java
> +            currentCommunicationDevice.broadCastConnectionStatus(ConnectionStatus.connected);
if we were to change what connected is, this is not the place to do so. Currently this will send a greet to the message to send queue and show "green" at the same time as sendGreet isn't blocking

2021-04-09 12:40 UTC, t-constantin commented on HiveAR/app/src/main/java/com/swarmus/hivear/activities/MainActivity.java
> +            currentCommunicationDevice.broadCastConnectionStatus(ConnectionStatus.connected);
in fact, I just changed in PR: https://github.com/SwarmUS/HiveAR/pull/48 to show yellow if physical connection established, but cellphone agent not initialized (no greet)
We will have more information that way

2021-04-09 12:41 UTC, g-lesssard commented on HiveAR/app/src/main/java/com/swarmus/hivear/activities/MainActivity.java
> +            currentCommunicationDevice.broadCastConnectionStatus(ConnectionStatus.connected);
Moved it to the onReceive() function when handling a greeting.

2021-04-09 13:03 UTC, t-constantin approved these changes

2021-04-09 13:04 UTC, merged